import type { EventItem } from "@/components/events/EventCard";

export const allEvents: EventItem[] = [
  {
    _id: "e1", slug: "menengai-crater-summit-apr-2026",
    title: "Menengai Crater Summit",
    trail: "Menengai Crater", activityType: "Hiking", difficulty: "Moderate",
    date: "2026-04-19", time: "6:00 AM",
    meetingPoint: "Shell Petrol Station, Nakuru-Nairobi Highway (opp. Menengai entrance)",
    priceKsh: 1500,
    description: "A half-day hike to the rim of one of Africa's largest calderas. The trail winds through wildflowers, geothermal vents and open grassland before delivering you to panoramic views over Nakuru town and the Rift Valley floor.",
    highlights: ["Panoramic views over Lake Nakuru and the Rift Valley", "Geothermal vents and hot springs along the trail", "Endemic wildflowers and highland birds", "Guided by certified Roam trail guides"],
    whatToBring: ["2L of water minimum", "Snacks / energy bars", "Hiking shoes or sturdy trainers", "Light jacket (cool at the rim)", "Sunscreen and hat", "National ID / Student ID", "Camera"],
    includedInPrice: ["Certified guide", "Trail brief and safety talk", "First aid coverage"],
    notIncluded: ["Personal hiking gear", "Park/crater access fees (if applicable)", "Lunch"],
    guide: "Brian K.",
    image: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=900&q=80",
  },
  {
    _id: "e2", slug: "mt-longonot-rim-apr-2026",
    title: "Mt. Longonot Rim Challenge",
    trail: "Mt. Longonot National Park", activityType: "Hiking", difficulty: "Challenging",
    date: "2026-04-26", time: "5:30 AM",
    meetingPoint: "Mt. Longonot National Park Gate, off the Naivasha–Narok Road",
    priceKsh: 2000,
    description: "The full crater circuit — 11.5km around Kenya's most dramatic volcano. An early start is essential. Expect steep ascents, exposed ridge walking and the kind of views that stay with you for years.",
    highlights: ["Full crater rim circuit at 2,776m", "Views of Lake Naivasha and the Rift Valley on both sides", "Wildlife including buffalo, baboons and Verreaux's eagles", "One of Kenya's most iconic summit experiences"],
    whatToBring: ["3L of water minimum", "High-energy snacks and lunch", "Proper hiking boots (non-negotiable)", "Warm layer for the summit", "Sunscreen, sunglasses and hat", "National ID", "Trekking poles (optional but helpful)"],
    includedInPrice: ["Certified guide", "Safety briefing", "First aid coverage"],
    notIncluded: ["KWS park entry fees (currently KSh 600 for citizens)", "Personal hiking gear", "Lunch"],
    guide: "Amina W.",
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=900&q=80",
  },
  {
    _id: "e3", slug: "lake-nakuru-flamingo-walk-may-2026",
    title: "Lake Nakuru Flamingo Walk",
    trail: "Lake Nakuru National Park", activityType: "Walk", difficulty: "Easy",
    date: "2026-05-02", time: "6:30 AM",
    meetingPoint: "Lake Nakuru National Park Main Gate, Nakuru",
    priceKsh: 1200,
    description: "A guided bird walk along the famous flamingo shores with an expert Roam birder. Early morning is peak activity time — bring binoculars and patience, the wildlife rewards are exceptional.",
    highlights: ["Lesser and greater flamingos on the shoreline", "Pelicans, cormorants, fish eagles and over 400 species recorded", "Expert bird identification guidance", "Gentle terrain suitable for all ages"],
    whatToBring: ["1.5L of water", "Light snack", "Binoculars if you have them", "Comfortable walking shoes", "Light jacket (early morning)", "National ID", "Camera with a zoom lens"],
    includedInPrice: ["Expert bird guide", "Species checklist booklet", "Safety coverage"],
    notIncluded: ["KWS park entry fees (KSh 600 citizens)", "Binoculars"],
    guide: "Cynthia M.",
    image: "https://images.unsplash.com/photo-1444464666168-49d633b86797?w=900&q=80",
  },
  {
    _id: "e4", slug: "eburu-forest-loop-may-2026",
    title: "Eburu Forest Loop",
    trail: "Eburu Forest", activityType: "Hiking", difficulty: "Moderate",
    date: "2026-05-10", time: "7:00 AM",
    meetingPoint: "Naivasha town stage (we carpool from here)",
    priceKsh: 1500,
    description: "A loop through one of the Rift Valley's most atmospheric forests — geothermal springs, Colobus monkeys, Bongo antelope and cool, misty conditions throughout. Bring layers.",
    highlights: ["Geothermal springs and steam vents in the forest", "Endangered Mountain Bongo and Colobus monkey sightings", "Rich endemic birdlife including African Green Ibis", "Peaceful trail with very few other hikers"],
    whatToBring: ["2L water", "Packed lunch", "Waterproof jacket (it gets misty)", "Hiking boots", "Sunscreen", "National ID"],
    includedInPrice: ["Certified guide", "Trail safety briefing"],
    notIncluded: ["Transport to Naivasha", "Lunch", "Personal gear"],
    guide: "Brian K.",
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=900&q=80",
  },
  {
    _id: "e5", slug: "hells-gate-gorge-may-2026",
    title: "Hell's Gate Gorge Hike",
    trail: "Hell's Gate National Park", activityType: "Hiking", difficulty: "Easy",
    date: "2026-05-17", time: "7:30 AM",
    meetingPoint: "Hell's Gate National Park Main Gate, Naivasha",
    priceKsh: 1800,
    description: "Walk through towering volcanic gorges with wildlife roaming freely alongside you — no vehicles, no fences. The gorge section is dramatic. Often combined with a gorge descent for the adventurous.",
    highlights: ["Towering volcanic rock columns and gorge walls", "Wildlife on foot — zebra, gazelle, buffalo", "Optional gorge descent with guide", "Inspired the landscape in Disney's Lion King"],
    whatToBring: ["2L water", "Snacks", "Sturdy shoes (gorge floor can be rocky)", "Swimwear if doing gorge dip", "Sunscreen and hat", "National ID"],
    includedInPrice: ["Guide", "Safety briefing"],
    notIncluded: ["KWS entry fees (KSh 600 citizens)", "Gorge descent fee (approx. KSh 600)", "Lunch"],
    guide: "David O.",
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=900&q=80",
  },
  {
    _id: "e6", slug: "menengai-crater-campout-may-2026",
    title: "Menengai Crater Rim Campout",
    trail: "Menengai Crater", activityType: "Camping", difficulty: "Moderate",
    date: "2026-05-23", time: "3:00 PM",
    meetingPoint: "Shell Petrol Station, Nakuru-Nairobi Highway (opp. Menengai entrance)",
    priceKsh: 3500,
    description: "An overnight camping experience at 2,272m on the crater rim. Arrive in the afternoon, set up camp, enjoy a campfire dinner, and wake to sunrise over the Rift Valley. All camping gear provided.",
    highlights: ["Camping at 2,272m on an active geothermal volcano", "Campfire and communal dinner under the stars", "Sunrise over Lake Nakuru and the Rift Valley", "Night sky stargazing away from city lights"],
    whatToBring: ["Warm sleeping clothes (it gets cold at night)", "Torch / headlamp", "Personal toiletries", "Camera", "National ID", "Any personal medication"],
    includedInPrice: ["Tents and sleeping bags", "Campfire dinner and breakfast", "Certified guide", "First aid kit"],
    notIncluded: ["Personal clothing and gear", "Snacks beyond meals"],
    guide: "Amina W.",
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=900&q=80",
  },
  {
    _id: "e7", slug: "lake-elementaita-bird-walk-may-2026",
    title: "Lake Elementaita Walk",
    trail: "Lake Elementaita", activityType: "Walk", difficulty: "Challenging",
    date: "2026-05-31", time: "6:00 AM",
    meetingPoint: "Elementaita junction off the Nairobi–Nakuru highway",
    priceKsh: 1400,
    description: "A full-day loop around a UNESCO World Heritage soda lake. Longer and more demanding than the Nakuru walk — varied terrain through lakeshore, rocky outcrops and scrubland.",
    highlights: ["Flamingos, pelicans and 400+ recorded species", "UNESCO World Heritage Site", "Verreaux's Eagle soaring over the escarpment", "Remote and peaceful — very few other visitors"],
    whatToBring: ["3L water", "Full packed lunch", "Binoculars", "Hiking boots", "Sunscreen and hat", "National ID"],
    includedInPrice: ["Expert guide", "Species checklist"],
    notIncluded: ["Transport", "Lunch"],
    guide: "Cynthia M.",
    image: "https://images.unsplash.com/photo-1516208813382-0b4e60c3c36f?w=900&q=80",
  },
  {
    _id: "e8", slug: "hyrax-hill-sunrise-jun-2026",
    title: "Hyrax Hill Sunrise Hike",
    trail: "Hyrax Hill, Nakuru", activityType: "Hiking", difficulty: "Easy",
    date: "2026-06-07", time: "5:45 AM",
    meetingPoint: "Hyrax Hill Museum entrance, Nakuru",
    priceKsh: 800,
    description: "A short, accessible sunrise hike above Nakuru town. Perfect for first-timers, families or anyone wanting a quick morning adventure before the day begins. Back in town by 9AM.",
    highlights: ["Nakuru sunrise from 85m above the town", "Archaeological museum at the base", "Baby-friendly — suitable for all ages and fitness levels", "Ideal introductory trail for newcomers to Roam"],
    whatToBring: ["1L water", "Light snack", "Comfortable shoes (trainers fine)", "Light jacket for early morning", "National ID"],
    includedInPrice: ["Guide", "Museum entry voucher"],
    notIncluded: ["Nothing — most inclusive hike we run"],
    guide: "Brian K.",
    image: "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=900&q=80",
  },
  // Cycling events
  {
    _id: "c1", slug: "hells-gate-mtb-apr-2026",
    title: "Hell's Gate MTB Ride",
    trail: "Hell's Gate National Park", activityType: "Cycling", difficulty: "Moderate",
    date: "2026-04-20", time: "7:00 AM",
    meetingPoint: "Hell's Gate National Park Gate, Naivasha",
    priceKsh: 1800,
    description: "A thrilling MTB circuit through volcanic gorges on gravel and dirt. Wildlife shares the trail — keep your eyes open for zebra and buffalo around corners.",
    highlights: ["Wildlife sightings on the trail", "Technical gorge sections for the adventurous", "Dramatic volcanic rock scenery", "Bike hire available at the gate"],
    whatToBring: ["Helmet (mandatory)", "Cycling gloves", "Water 2L", "Snacks", "National ID", "Padded shorts recommended"],
    includedInPrice: ["Guide", "Safety briefing"],
    notIncluded: ["KWS entry fee", "Bike hire (approx. KSh 800)", "Lunch"],
    guide: "David O.",
    image: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=900&q=80",
  },
  {
    _id: "c2", slug: "rift-valley-road-ride-apr-2026",
    title: "Rift Valley Road Ride",
    trail: "Nakuru–Naivasha Road", activityType: "Cycling", difficulty: "Moderate",
    date: "2026-04-27", time: "6:30 AM",
    meetingPoint: "Nakuru Athletics Club car park, off Kenyatta Avenue",
    priceKsh: 1500,
    description: "A 35km road ride with panoramic views of the Great Rift Valley escarpment. Mostly flat with one steady climb. Road bikes and hybrids both suitable.",
    highlights: ["Rift Valley escarpment views throughout", "Mostly smooth tarmac — beginner-friendly", "Naivasha finish with optional lunch stop", "Carpooling back to Nakuru arranged"],
    whatToBring: ["Helmet (mandatory)", "Road or hybrid bike", "Water 2L", "Snacks", "Cycling kit / comfortable clothes", "National ID"],
    includedInPrice: ["Lead guide", "SAG support vehicle for the group"],
    notIncluded: ["Bike", "Lunch", "Return transport (arranged but not included)"],
    guide: "David O.",
    image: "https://images.unsplash.com/photo-1517649763962-0c623066013b?w=900&q=80",
  },
  {
    _id: "c3", slug: "nakuru-sunday-ride-may-2026",
    title: "Nakuru Sunday Community Ride",
    trail: "Nakuru Town Circuit", activityType: "Cycling", difficulty: "Easy",
    date: "2026-05-04", time: "7:00 AM",
    meetingPoint: "Nakuru Athletics Club car park, off Kenyatta Avenue",
    priceKsh: 500,
    description: "Our weekly social ride — a relaxed 15km loop around Nakuru. All bikes welcome. All levels welcome. This is the ride where strangers become riding partners.",
    highlights: ["Relaxed pace — no one gets dropped", "All bike types welcome (MTB, road, hybrid)", "Coffee stop at the halfway point", "Weekly recurring — every Sunday"],
    whatToBring: ["Any bike in working condition", "Helmet (mandatory)", "Water", "Good energy"],
    includedInPrice: ["Group ride leader", "Coffee stop"],
    notIncluded: ["Bike hire"],
    guide: "Community-led",
    image: "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=900&q=80",
  },
];
