import type { Product } from "@/types/product";

export const allProducts: Product[] = [
  {
    id: "p1",
    slug: "nnts-trail-tee",
    name: "NNTS Trail T-Shirt",
    category: "Apparel",
    price: 2500,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80",
    description: "Lightweight, moisture-wicking cotton blend tee with the NNTS logo. Built for trail days and community events.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    inStock: true,
    featured: true,
  },
  {
    id: "p2",
    slug: "nnts-cap",
    name: "NNTS Trail Cap",
    category: "Apparel",
    price: 1200,
    image: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=600&q=80",
    description: "Six-panel structured cap with embroidered NNTS logo. Adjustable strap — one size fits most.",
    inStock: true,
    featured: true,
  },
  {
    id: "p3",
    slug: "trail-water-bottle",
    name: "NNTS Insulated Water Bottle (1L)",
    category: "Gear",
    price: 1800,
    image: "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&q=80",
    description: "Double-wall stainless steel bottle. Keeps water cold for 24 hours. Leak-proof lid. Ideal for long trail days.",
    inStock: true,
    featured: true,
  },
  {
    id: "p4",
    slug: "neck-buff",
    name: "Trail Neck Buff",
    category: "Accessories",
    price: 800,
    image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
    description: "Versatile seamless tube — wear as a buff, headband, beanie or face cover. UV protection. NNTS branded.",
    inStock: true,
  },
  {
    id: "p5",
    slug: "trail-notebook",
    name: "NNTS Trail Notebook",
    category: "Accessories",
    price: 600,
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&q=80",
    description: "A5 hardcover notebook with NNTS trail cover art. Waterproof pages. For route notes, journaling and ideas.",
    inStock: true,
  },
  {
    id: "p6",
    slug: "performance-socks",
    name: "Trail Socks (2-pack)",
    category: "Gear",
    price: 700,
    image: "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&q=80",
    description: "Cushioned, anti-blister hiking socks. Arch support panel and reinforced heel and toe. Fits UK 6–11.",
    sizes: ["One Size"],
    inStock: true,
  },
  {
    id: "p7",
    slug: "nnts-hoodie",
    name: "NNTS Camp Hoodie",
    category: "Apparel",
    price: 3800,
    originalPrice: 4500,
    image: "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=600&q=80",
    description: "Midweight pullover hoodie perfect for camp evenings and cool mornings on the trail. NNTS wordmark on chest.",
    sizes: ["S", "M", "L", "XL"],
    inStock: true,
    featured: true,
  },
  {
    id: "p8",
    slug: "trail-bandana",
    name: "Cotton Trail Bandana",
    category: "Accessories",
    price: 500,
    image: "https://images.unsplash.com/photo-1613695296490-4a97df574b45?w=600&q=80",
    description: "Classic 100% cotton bandana in NNTS forest green. Dozens of uses on the trail — cooling, dust, sun protection.",
    inStock: true,
  },
];
